tabuada = int(input("Escreva o número que quer descobrir a tabuada: "))
t1 = tabuada * 1
print(f"{tabuada} X 1 = {t1}")
t2 = tabuada * 2
print(f"{tabuada} X 2 = {t2}")
t3 = tabuada * 3
print(f"{tabuada} X 3 = {t3}")
t4 = tabuada * 4
print(f"{tabuada} X 4 = {t4}")
t5 = tabuada * 5
print(f"{tabuada} X 5 = {t5}")
t6= tabuada * 6
print(f"{tabuada} X 6 = {t6}")
t7 = tabuada * 7
print(f"{tabuada} X 7 = {t7}")
t8 = tabuada * 8
print(f"{tabuada} X 8 = {t8}")
t9 = tabuada * 9
print(f"{tabuada} X 9 = {t9}")
t10 = tabuada * 10
print(f"{tabuada} X 10 = {t10}")